### ISSUE TITLE
Add diode in the Circuit Elements

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#2608] opened 2021-11-17 17:48 UTC
**Describe the solution you'd like**
Add diode as a new feature in the circuit elements

**Are you working on this? (Yes/No)**
Yes, I am working on this issue

**Comment by tachyons** [comment] 2021-11-20 00:35
Duplicate of https://github.com/CircuitVerse/CircuitVerse/issues/1992

**Closed by tachyons** 2021-11-20 00:35 UTC
Labels: 🌟 feature
