### ISSUE TITLE
Redesign error 404 page

### ISSUE THREAD

**Issue by khareyash05** [CircuitVerse/CircuitVerse#2599] opened 2021-11-15 11:25 UTC
I would like to redesign error 404 page

![image](https://user-images.githubusercontent.com/60147732/149188227-e45dd7ed-cc24-4850-b47a-ebe6b5d790bc.png)

**Comment by Sayan-Maity** [comment] 2021-12-11 06:58
@khareyash05 , are you still working on this issue? Or I shall contribute in it

**Comment by khareyash05** [comment] 2021-12-11 10:31
@Sayan-Maity  I am waiting for assignment and I think you too should wait till then

**Comment by Sayan-Maity** [comment] 2021-12-11 10:31
@khareyash05 , yeahhh

**Comment by khareyash05** [comment] 2022-01-12 17:09
@vedant-jain03 @tachyons have a look at this issue

**Comment by vedant-jain03** [comment] 2022-01-12 17:29
> @vedant-jain03 @tachyons @gr455 have a look at this issue

cc @nitin10s

**Comment by Subhraneel77** [comment] 2022-02-28 18:53
Can I give it a try?

**Comment by gr455** [comment] 2022-03-02 05:04
Sure, we could use a better looking 404 page

**Comment by sahilsuman933** [comment] 2022-08-19 18:32
I would love to work on this issue. @vedant-jain03, can you please assign this issue to me?

**Comment by Gairick52** [comment] 2022-10-08 09:49
why not put error 404 in Bold text  and in next line we could add oops the page you are looking for could not be found in an attractive logo/template and in beside that logo it will appear in return to homepage in this size only and we could also add an extra tab for troubleshooting the possible causes for error 404

**Comment by Gairick52** [comment] 2022-10-08 10:22
https://www.figma.com/file/4KxvZ6qM4EUjidf8N6VDD1/Untitled?node-id=4%3A3

**Comment by Prerna-0202** [comment] 2022-10-08 20:09
> https://www.figma.com/file/4KxvZ6qM4EUjidf8N6VDD1/Untitled?node-id=4%3A3

You can post the designs in the #ux slack channel, and try the theme should be consistent with the site, also you can take reference for design by https://github.com/CircuitVerse/CircuitVerse/pull/1341, and once your design is approved by core team members, then you can make a pull request.

**Comment by Gairick52** [comment] 2022-10-09 02:30
@Prerna-0202 thank you very much for your guidance till now,i just have one doubt can you please tell me how to find ux slack channel of circuitverse

**Comment by Rutwik187** [comment] 2022-11-11 18:21
hi. I am really good at designing [figma] and programming [vue , react]  web pages. If the issue is still open I would love to contribute.

**Comment by Prerna-0202** [comment] 2023-05-14 18:58
> is it open?

Yes

**Comment by whogurdevil** [comment] 2023-08-21 16:57
I want to work on this

**Comment by Prerna-0202** [comment] 2023-08-24 17:54
> I want to contribute in this

Go ahead 👍

**Closed** 2023-09-13 14:17 UTC
Labels: 🌟 feature
