### ISSUE TITLE
Change Password page lacks Bootstrap

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#502] opened 2019-11-01 11:15 UTC
**Is your feature request related to a problem? Please describe.**
Change your password page lacks bootstrap.

**Describe the solution you'd like**
Add bootstrap buttons to keep a consistency between all buttons.

**Additional context**
Screenshot has been attached.

![bootstrap](https://user-images.githubusercontent.com/42520146/68021253-ed82b080-fcc6-11e9-995e-5b722308d093.PNG)

**Comment by ankitkataria** [comment] 2019-11-09 18:27
Duplicate of #367

**Closed by ankitkataria** 2019-11-09 18:27 UTC
