### ISSUE TITLE
Add pre signout message before signing out

### ISSUE THREAD

**Issue by pankaj-2503** [CircuitVerse/CircuitVerse#4773] opened 2024-02-27 17:03 UTC
### Is your feature request related to a problem? Please describe

Before signout there should be pop up message like do you really want to sign out then user can sign out.
Right now it's directly signing out without pop-message.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/90036864/7d2804e7-02e3-4876-b2a1-655c5f778ac1)

### Describe the solution you'd like

Adding pre-singout message like do you want to sign out.

### Are you working on this?

Yes

**Comment by upsaurav12** [comment] 2024-02-28 02:21
@pankaj-2503 this issue was already raised #4717

**Comment by tanmoysrt** [comment] 2024-02-28 05:05
Duplicate of #4717

**Closed by tanmoysrt** 2024-02-28 05:05 UTC
Labels: 🌟 feature, pending triage
