### ISSUE TITLE
Loader redesign proposal

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerse#468] opened 2019-10-28 13:46 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the loader is a blue diamond folding animation. For better impact, we may replace it with a new loader. Would look great if opposite arms of links in the circuitverse logo light up alternatively.

**Describe the solution you'd like**
The new proposed loader might build up on top of the [circuitverse logo](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/img/favicon.ico) 

**Describe alternatives you've considered**

**Additional context**
![loadercc](https://user-images.githubusercontent.com/25405707/67683240-09c8d980-f9b7-11e9-8c6f-68d10b6bb139.PNG)
Intended for GCI'19.

**Are you working on this? (Yes/No)**
No.

**Comment by ankitkataria** [comment] 2019-10-28 17:06
Duplicate of #466

**Comment by fluctix** [comment] 2019-11-09 12:37
@Parikshit-Hooda Did you mean something like this:
![ezgif com-resize](https://user-images.githubusercontent.com/40538506/68528657-af673b80-031b-11ea-884c-abc2f7376e6b.gif)

**Comment by thiefie** [comment] 2020-02-29 10:44
we would need a new one for the new logo

**Closed** 2020-03-08 00:09 UTC
Labels: gci19, no-issue-activity
