### ISSUE TITLE
Notifications Page is lack luster

### ISSUE THREAD

**Issue by bhutani2002** [CircuitVerse/CircuitVerse#2929] opened 2022-02-12 20:23 UTC
**Is your feature request related to a problem? Please describe.**
The notifications Webpage is completely lack lustered with no functioning of buttons and lack of better user experience on the frontend side. The page is not visually appealing. 

**Describe the solution you'd like**
To make the webpage user friendly and appealing.

Providing some popups.....Showing each of the notifications received by the user in card or box like format on the webpage, whenever the user login . As to provide easy accessibility to the notifications without the inconvenience of finding the notifications on their mails each time.

And also as unread notifications are building up on the user's profile, will provide a dot or something like that on the tab....As of what we get on slack or WhatsApp when some notifications of ours are left to be read. And as soon as we read the messages that dot or no. disappears.

**Additional context**
![image](https://user-images.githubusercontent.com/84590758/153726585-d5b323e5-7b07-4ac4-aba8-e18dca617e77.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by bhutani2002** [comment] 2022-02-12 20:29
Hey @gr455 @tachyons @vedant-jain03 @Prerna-0202 can you provide some suggestions on what is been required to be done on this page. Since I know this is in the project list of gsoc2022 too, so I needed some feedback on what you all expect the content to be on this page . 

I have mentioned some suggestions on my issue above. 
I don't know how I'll do this, but will definitely make the page better😂.

Thank You

**Comment by Prerna-0202** [comment] 2022-02-13 09:55
Hey @bhutani2002, Thanks for raising an issue but this is  duplicate of #2321

**Closed** 2022-02-13 09:56 UTC
Labels: duplicate, 🌟 feature
