### ISSUE TITLE
Primary buttons all over the site increase resource usage because of hover effect + they don't get clicked properly 

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3607] opened 2023-02-22 16:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the buttons are hovered with the cursor from the bottom and the the cursor is within the 20-25% bottom area of the button , then because of hover effect they translate upwards but as soon as they go up the button is out of the hover of cursor so it tries to come back down and it gets hovered again ... this cycle continues and the button goes in and out of hover state ... as a result it results in significantly higher resource usage ... (while using it in a computer of my lab this make the fans of the computer ramp up + site being sluggish. ) 

plus because of such high translate value the button when it is clicked they don't get clicked and we need to change the mouse position on to the button again to click the button

### Steps To Reproduce

1. Go to [circuitverse.org ](https://circuitverse.org/) 
2. find the Launch simulator button (or any button in green color)
3. hover with your mouse at the bottom of the button.
4. you can go to dev tools and remove transition effect from button, to see the issue clearly
5. you can open task manger and see cpu usage increasing.

### Expected Behavior

when the cursor is over any point of the button it should be selected and go into hover state and not go in and out of hover state.
also on clicking the button when selected should really click the button instead of just changing the hover  state.

### Screenshots

https://user-images.githubusercontent.com/96580571/220685010-db6c9be1-4afe-46bc-a9ac-eb8b06fc7302.mp4

### Device Information [optional]

```markdown
- OS: Any
- Browser: Any (specifically firefox)
- version: web
```

### Are you working on this issue?

Yes

**Comment by nikhilhvr** [comment] 2023-02-24 08:16
I'd like to contribute to this issue and will start investigating the cause of the problem.

Let me know if you're also working on this. Excited to contribute!

**Comment by cipherbhai** [comment] 2023-02-24 14:03
Sorry @Arnabdaz but this button is working fine. I don't think so that it requires any changes. May be this issue is resolved.

**Comment by vedant-jain03** [comment] 2023-02-25 04:23
Thanks for suggestion @Arnabdaz, we can refer it for the future when we are using primary buttons many a times in the application, although this time in GSoC we are thinking of shifting every thing to view components, we will refer this for buttons!

Closing it for now....

**Closed by vedant-jain03** 2023-02-25 04:23 UTC
Labels: 🐞 bug, pending triage
