### ISSUE TITLE
Broken icons

### ISSUE THREAD

**Issue by pranay-simejia** [CircuitVerse/CircuitVerse#2212] opened 2021-04-12 19:51 UTC
**Describe the bug**

**To Reproduce**
1. Go to ['sign_in page'](https://circuitverse.org/users/sign_in)
2. See an error
3. Go to [footer](https://circuitverse.org/)
4. See an error

**Expected behavior**
 Icons should be loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/70064696/114452838-86289a00-9bf6-11eb-9eb6-65cfa4dce9a0.png)
![image](https://user-images.githubusercontent.com/70064696/114468515-40290180-9c09-11eb-872d-e5635460bd8c.png)

**Are you working on this issue? (Yes/No)**
No.

**Comment by anmolkohli13** [comment] 2021-04-14 13:19
@pranay-simejia can you mention in which OS and browser are you experiencing this?

**Comment by pranay-simejia** [comment] 2021-04-14 14:15
windows and chrome @anmolkohli13

**Comment by anmolkohli13** [comment] 2021-04-14 15:31
@pranay-simejia are you experiencing this issue every time you open the sign-in page? Also, I am not able to reproduce the error 🤔maybe this happened due to some network issue

**Comment by pranay-simejia** [comment] 2021-04-15 15:03
@anmolkohli13 yes, I even tried clearing my cache and cookies. 
But I didn't face the same issue in any other browser. You got on how to fix this, or should I close this issue?

**Comment by anmolkohli13** [comment] 2021-04-15 15:46
I am not facing this issue nor able to reproduce it. I think if you continue to face this issue and others face it too then you should work on fixing this otherwise close this issue.

**Closed** 2021-04-18 20:49 UTC
Labels: 🐞 bug
