### ISSUE TITLE
Centering the social icons in the footer

### ISSUE THREAD

**Issue by KoushikAD1234** [CircuitVerse/CircuitVerse#2720] opened 2021-12-16 06:57 UTC
**Describe the bug**
There is a misalignment of icons and there is non-uniform padding and margin on the icons.

**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to Footer section
3. See the social icons (Twitter, LinkedIn, Facebook)

**Expected behavior**
The social media icon is must align on center of the box.

**Screenshots**
Before:-

![Screenshot (205)](https://user-images.githubusercontent.com/72178398/146322922-8d9a8f9a-d6f7-448a-b750-2998de1c499f.png)
![Screenshot (206)](https://user-images.githubusercontent.com/72178398/146322938-a8806bd5-3bb2-4cbc-baa3-5d5abe2b08fd.png)

After:-

![Screenshot (203)](https://user-images.githubusercontent.com/72178398/146322833-cc029fa5-b435-4752-be44-8d9a656c2231.png)
![Screenshot (204)](https://user-images.githubusercontent.com/72178398/146322840-c500779e-5eac-4cd8-9961-fd6affce9fa7.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by rucha0702** [comment] 2021-12-16 09:59
@KoushikAD1234  The exact same issue has already been created. Check out #2712

**Comment by denver-39** [comment] 2021-12-28 06:13
@KoushikAD1234  I've fixed this issue should I make PR
![Screenshot 2021-12-28 114145](https://user-images.githubusercontent.com/88855792/147534150-0940c991-ab9d-444f-a0fc-9196111e76f7.png)

**Comment by KhanFiza896** [comment] 2022-01-25 11:06
can i work on this issue?

**Comment by vedant-jain03** [comment] 2022-01-25 17:48
@KoushikAD1234 Kindly approve the issue in the slack UX channel first before opening the issue as it may lead to unnecessary issue numbers.

**Comment by Palaksharma23** [comment] 2022-01-31 10:31
Duplicate of #2712

**Closed** 2022-01-31 10:31 UTC
Labels: 🐞 bug
