### ISSUE TITLE
Added contributing.md file

### ISSUE THREAD

**Issue by la2798** [CircuitVerse/CircuitVerse#176] opened 2019-03-03 13:02 UTC
#### I am submitting a -
* [] ** Added Feature**

#### Enchancement
Added the CONTRIBUTING.md file which has the steps to raise a PR and also steps for how to open an Issue which will help people who are new to open source contribution.

**Comment by armudgal** [comment] 2019-03-03 14:15
Hi, it's a duplicate of #146, @Parikshit-Hooda message conveyed that if the PR you are working on *does not* have an existing issue, then the issue needs to be created.

**Closed by armudgal** 2019-03-03 14:15 UTC
Labels: duplicate
