### ISSUE TITLE
Sticky footer problem in 404 error page

### ISSUE THREAD

**Issue by Kartikay304** [CircuitVerse/CircuitVerse#2520] opened 2021-10-04 06:36 UTC
**Describe the bug**
The footer is not in a fixed position (footer is not sticky)

**To Reproduce**
<h2>Steps to reproduce the behavior:</h2>

1. Go to 'any invalid page'

2. Eg: https://circuitverse.org/sasdsada

3. Except root page all pages have the similar type of issue.

4. Then change screen zoom

5. See error

**Expected behavior**
<h3>Footer should be sticky.</h3>

<hr>

<h2>Screenshots</h2>
<br><br>

![sticky footer](https://user-images.githubusercontent.com/40604582/135803766-ca1984b6-2991-4ef4-8635-5c0cd21c0ce4.png)

![footeerrr](https://user-images.githubusercontent.com/40604582/135889511-cce00935-00b9-4824-8c44-b0d4df207e79.png)

**Device Information [optional]:**
 - OS: Win 11 Dev Build
 - Browser Edge 
 - Version 94.0.992.38 (Official build) (64-bit)

**Are you working on this issue? (Yes/No)**
No, @ShreyaPrasad1209  Can you could label this issue as "good first issue."

**Comment by vedant-jain03** [comment] 2021-10-04 10:08
@Kartikay304 I use windows 10 and I am not able to see the error I mean on my screen at 404 page I can see the correct placing of the footer!

**Comment by prsndp** [comment] 2021-10-04 18:44
@Kartikay304 I guess it is not a bug. Obviously, if we visit an unknown page then it will happen, we can't design for unknown pages, For example, the Microsoft official site also has the same issue.

**Comment by ShreyaPrasad1209** [comment] 2021-10-05 07:41
I can see this issue in Mac. @prsndp in case of unknown page, websites send back a 404 page which can be easily designed.
@Kartikay304 please go ahead

**Comment by Kartikay304** [comment] 2021-10-05 08:45
Okay working on it.

**Comment by Aashishkushwaha** [comment] 2021-10-05 08:57
Hi @ShreyaPrasad1209  Can I work on resolving this footer issue ?

**Comment by Kartikay304** [comment] 2021-10-05 10:10
> Hi @ShreyaPrasad1209 Can I work on resolving this footer issue ?

Currently I am working in this issue..

**Comment by pavanjoshi914** [comment] 2021-10-06 04:54
Do you say except the home page every page has this issue? 

Footer is designed as a bootstrap ``fluid-container``` hence it takes entire horizontal space. which is correct behaviour

On any page, the footer is always stuck to the end of the page and that seems correct behaviour. 

it is just homepage has more vertical length than others and fills the zoomed page completely, in others it doesn't happen that is why you can see the gap.

I don't think it is  any problem with stickiness off the footer

cc @ShreyaPrasad1209

**Closed** 2021-11-26 17:29 UTC
Labels: 🐞 bug, Hacktoberfest
