### ISSUE TITLE
🐞 Bug: Content and button are not visible in svg option

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4412] opened 2023-12-22 10:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Simulator for converting the diagram to SVG the buttons and contents are not visible like PNG , JPEG, BMP, GIF

### Steps To Reproduce

1. Go to 'https://circuitverse.org/simulator'
2. Click on 'Download as image'
![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/d86f713c-93aa-463b-8acc-5348dc0455b5)
3. Click on SVG option

### Expected Behavior

![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/2090cd87-4679-44aa-afbb-f10df5ae7019)

### Screenshots

![image](https://github.com/CircuitVerse/cv-frontend-vue/assets/116784047/2f3862b7-6e86-42a6-8bd5-b32df6d1b1eb)

### Device Information [optional]

```markdown
- OS: Windows 
- Browser: chrome
- version: 120
```

### Additional context

You can check may this is from your  side also 

### Are you working on this issue?

Yes

**Comment by RahulRudra81** [comment] 2023-12-22 15:42
Can you assign it to me?

**Comment by upsaurav12** [comment] 2023-12-23 11:02
how can improve that or what can solution

**Comment by tanmoysrt** [comment] 2023-12-26 13:44
Duplicate of #4134

**Closed by tanmoysrt** 2023-12-26 13:44 UTC
Labels: 🐞 bug, pending triage
