### ISSUE TITLE
🐞 Bug Footer section alignment

### ISSUE THREAD

**Issue by himavamsi12** [CircuitVerse/CircuitVerse#4840] opened 2024-03-21 18:32 UTC
![image](https://github.com/CircuitVerse/CircuitVerse/assets/124918703/a523e5ea-6a30-4c0e-825f-0ca47083dc9d)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the footer section has improper alignment and the image is at the center also the copyright trademark is at the left.I will make it an attractive footer section.

### Steps To see

1. go to the website of circuitverse
2. then scroll down to the footer section 
3. see the alignment of the footer section

### Expected Behavior

All the elements are at the center like the heading, image..

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by himavamsi12** [comment] 2024-03-21 18:35
hi @tanmoysrt  sir,

can i work on it

**Comment by tanmoysrt** [comment] 2024-03-21 18:37
> hi @tanmoysrt sir,
> 
> can i work on it

You should provide what the current design and what design you want to see in update

**Comment by himavamsi12** [comment] 2024-03-21 18:40
Sir, The copyright trademark should be at the center and I will arrange the image to the right of it. 
There is more space around the elements all the elements are grouped at center

**Comment by tanmoysrt** [comment] 2024-03-21 18:49
The isssue and design is already here https://github.com/CircuitVerse/CircuitVerse/issues/4563
So, closing this issue as duplicate of #4563

**Closed by tanmoysrt** 2024-03-21 18:49 UTC
Labels: 🐞 bug, pending triage

**Comment by himavamsi12** [comment] 2024-03-23 05:58
But on the website, it doesn't align with the appropriate positions what is the issue?

**Comment by tanmoysrt** [comment] 2024-03-23 06:19
> But on the website, it doesn't align with the appropriate positions what is the issue?


The PR's a re not merged yet, under review.
You should check recent issues + development website locally before raising issue

**Comment by himavamsi12** [comment] 2024-03-23 06:33
ok
