### ISSUE TITLE
Allow circuit tabs to be re-ordered

### ISSUE THREAD

**Issue by richardpawson** [CircuitVerse/CircuitVerse#1923] opened 2020-11-17 09:59 UTC
At present (unless I have missed something), the order in which circuit tabs are displayed within a project is determined only by the order in which they were created. This can be inconvenient - I often want to create a new sub-circuit that's related to an existing one and would like to have the tabs next to each other. 

As in most IDEs, I'd like just to be able to drag a tab and drop it on top of another tab (or between two tabs - I don't care which) to move the tab.

**Comment by satu0king** [comment] 2020-11-17 13:41
Duplicate of #443 #1268

**Comment by satu0king** [comment] 2020-11-17 13:43
@gr455, @shubhankarsharma00  this would be an interesting task for you.

**Comment by satu0king** [comment] 2020-11-17 14:21
A possible solution to consider
* Circuit ordering needs to be part of saved data
* Circuits are ordered according to saved data ordering on load
* Ordering is maintained in UI when editing, ordering

**Comment by satu0king** [comment] 2020-11-29 18:59
Implemented

**Closed by satu0king** 2020-11-29 18:59 UTC
Labels: duplicate
