### ISSUE TITLE
No redo option available

### ISSUE THREAD

**Issue by vkassingh** [CircuitVerse/CircuitVerse#1856] opened 2020-10-30 04:33 UTC
**Is your feature request related to a problem? Please describe.**
There is only undo option in the user interface. So I would like to add a redo option there to make the circuit verse more user friendly.

**Additional context**
![bug1](https://user-images.githubusercontent.com/42089632/97660215-e5ef1680-1a96-11eb-8d56-dc7e70a1c047.JPG)

**Are you working on this? (Yes/No)**
Yes I would like to work on this issue

**Comment by satu0king** [comment] 2020-11-01 15:39
Duplicate of #376 #redo

**Comment by Palaksharma23** [comment] 2021-10-01 12:22
I want to work on this issue , Can you please assign it to me

**Comment by Prerna-0202** [comment] 2022-01-15 18:30
duplicate of  #376

**Closed by Prerna-0202** 2022-01-15 18:30 UTC
Labels: 🌟 feature
