### ISSUE TITLE
Adding padding to few buttons

### ISSUE THREAD

**Issue by Shilpashreemr** [CircuitVerse/CircuitVerse#2665] opened 2021-12-03 01:54 UTC
This is a enhancement to make the buttons easily read - able, by adding padding  around few of the buttons.

The buttons like:
![Screenshot (485)_LI](https://user-images.githubusercontent.com/86882411/144531133-4680037b-d45d-4232-a00e-e91a15e483ce.jpg)
![Screenshot (484)_LI](https://user-images.githubusercontent.com/86882411/144531152-505578dd-a21d-4fb8-80e0-8a0605b821f8.jpg)

Are you working on the issue ? (Yes/No)
Yes , I am working on the issue.

**Comment by vedant-jain03** [comment] 2021-12-03 03:21
I think this is duplicate of #2652

**Closed** 2021-12-03 08:17 UTC
Labels: 🌟 feature
