### ISSUE TITLE
🐞 Bug : User Details Dropdown / Sign In button is not responsive on the navbar of simulator 

### ISSUE THREAD

**Issue by ShubhaamTiwary** [CircuitVerse/CircuitVerse#4493] opened 2024-01-02 10:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the upper right corner of the simulator page The user information/sign-in button is inactive.
At 100% zoom (the default view), the entire user's details dropdown when logged in and the Sign In button when logged out are cut off. 

### Steps To Reproduce

1. Go to https://circuitverse.org/simulator
2. As you can see in the top-right corner, the user details are not responsive and is getting cut.
3. If you have not logged in, then the Sign In button is not responsive and is getting cut.

### Expected Behavior

The sign-in button or The user details dropdown should not get cut and should be responsive .

### Screenshots

Bug :
<img width="100" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/89575981/6a415796-49c6-4cfa-83e7-bc02a683ae15">   
<br>
<img width="100" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/89575981/acdce4c3-04a0-4f90-888c-cb837f864c01">

Expected : 
<img width="100" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/89575981/d30c3beb-b5b9-4890-8e61-69994088b5d0">

<img width="100" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/89575981/eabfbabc-2aca-4e5c-8049-ceb69d5f01d2">

### Are you working on this issue?

Yes

**Comment by ShubhaamTiwary** [comment] 2024-01-02 10:55
@tanmoysrt Can you confirm this bug , and if this is valid, then please assign this task to me?

**Comment by tanmoysrt** [comment] 2024-01-02 18:07
Duplicate of #4114

**Closed by tanmoysrt** 2024-01-02 18:07 UTC
Labels: 🐞 bug, pending triage
