### ISSUE TITLE
Development on Gitpod failing

### ISSUE THREAD

**Issue by sakshi-2412** [CircuitVerse/CircuitVerse#2663] opened 2021-12-02 15:25 UTC
**Describe the bug**
After following the steps mentioned on the page - [`Development on Gitpod`](https://github.com/CircuitVerse/CircuitVerse/wiki/Development-on-Gitpod), all ports can be made public except port 3000 as it is not served. I am not sure if this problem is particular to some users or to all of them.   

**To Reproduce**
1. Go to 'gitpod.io/#https://github.com/CircuitVerse/CircuitVerse'.
2. Click on 'Ports: __, __, __'  located in bottom right. 
3. Scroll to 'GITPOD WORKSPACE' on left side.

**Expected behavior**
Port 3000 to be open and preview of CircuitVerse to load automatically.

**Screenshots**
Problem:
![ports 1](https://user-images.githubusercontent.com/85152262/144447112-1580dce3-28fc-42e0-8073-5db2283e2673.jpeg)

Expected:
![ports 2](https://user-images.githubusercontent.com/85152262/144448217-e3409b66-b780-4f62-aed9-e339851f801a.jpeg)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96.0.4664.45

**Additional context**
I finally solved this issue by following the steps mentioned on Slack community in a reply to someone who faced similar problem.

![setup gitpod](https://user-images.githubusercontent.com/85152262/144450260-1723c036-47a3-44af-825c-86b2306d05d2.png)

If this is an issue that is faced by many users, then the page  [`Development on Gitpod`](https://github.com/CircuitVerse/CircuitVerse/wiki/Development-on-Gitpod) should be updated.

**Are you working on this issue? (Yes/No)**
Yes (if the solution is to just update the wiki page)

**Comment by Prerna-0202** [comment] 2021-12-02 18:04
@sakshi-2412, For serving 3000 port we have to run a command  "bundle exec rails s"  in our terminal and It is mentioned on the page "Development on gitpod" 
![Screenshot (35)](https://user-images.githubusercontent.com/89515816/144478007-570f8094-39cb-4ff5-8192-f8570100849c.png)

**Comment by sakshi-2412** [comment] 2021-12-02 18:21
Yes that worked, thanks! :smiley: It was confusing since the command is given after the preview is already loaded and port 3000 is serving.

**Comment by vedant-jain03** [comment] 2021-12-03 03:22
@sakshi-2412 If the issue is recovered kindly close it.

**Closed** 2021-12-03 05:50 UTC
Labels: 🐞 bug
