### ISSUE TITLE
fix: Border in footer social media links look odd.

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2590] opened 2021-11-05 10:46 UTC
**Describe the bug**
Border in social media links look odd.

**To Reproduce**
1. Go to 'circuitverse.org'
3. Scroll down to 'Footer'

**Expected behavior**
Remove the border

**Screenshots**
![bandicam 2021-11-05 16-13-42-250](https://user-images.githubusercontent.com/76901313/140498856-f7dfc8d8-726a-4dfd-b107-7c959fb161ba.jpg)

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by dhruvsol** [comment] 2021-11-05 10:58
i am working on it

**Comment by tachyons** [comment] 2021-11-14 10:05
Can you get this approved on #ux channel first

**Comment by dhruvsol** [comment] 2021-11-14 15:53
@tachyons  where is this channel??

**Comment by tachyons** [comment] 2021-11-14 16:29
https://circuitverse.org/slack

**Comment by nitin10s** [comment] 2021-11-15 06:02
A hover effect was added on purpose. Please confirm if the issue is valid by a maintainer before sending PRs. Closing this.

**Closed by nitin10s** 2021-11-15 06:02 UTC
Labels: 🐞 bug
