### ISSUE TITLE
Feature: include "Get it on Google Play" button in footer

### ISSUE THREAD

**Issue by Prajyot70** [CircuitVerse/CircuitVerse#4414] opened 2023-12-22 17:29 UTC
### Is your feature request related to a problem? Please describe

There isn't any information available on the Circuitverse website about the Circuitverse app available on the play store for Android. Due to because of this users might not come to know about the Circuitverse application on google play store.

### Describe the solution you'd like

Add a button to the footer of Circuitverse website redirecting to the Circuitverse application page on google play store, so that users will come to know about the Circuitverse app and can directly get redirected to google play store to install it.

### Are you working on this?

Yes

**Comment by Deeppjp116** [comment] 2023-12-23 04:56
I am working on this feature

**Comment by tanmoysrt** [comment] 2023-12-26 14:05
Duplicate of #4088

**Closed by tanmoysrt** 2023-12-26 14:05 UTC
Labels: 🌟 feature, pending triage
