### ISSUE TITLE
Show password seemed off in login page

### ISSUE THREAD

**Issue by abstrekt** [CircuitVerse/CircuitVerse#1253] opened 2020-03-20 08:07 UTC
**Describe the bug**
In the log-in page, the show password button seemed off, please refer the screenshots

**Screenshots**
![Firefox_Screenshot_2020-03-20T08-05-57 205Z](https://user-images.githubusercontent.com/42478217/77145892-c1b66a80-6aaf-11ea-964e-4529724c82f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 pro 64x
 - Browser Firefox 
 - Version 74.0 32bit

**Additional context**

**Are you working on this issue? (Yes/No)**
Yep

**Comment by MrBartusek** [comment] 2020-03-20 10:42
Duplicate of #769

**Closed** 2020-03-21 11:04 UTC
