### ISSUE TITLE
Launch and More option in embed mode are redirect to different project

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#1471] opened 2020-05-29 15:21 UTC
**Describe the bug**
go to https://circuitverse.org/users/3642 open any circuit (other then the latest circuit) and view it. In view mode select More or Launch it will open latest circuit.

**To Reproduce**
see issue problem

**Expected behavior**
should open the current project instead of latest one.

**Screenshots**

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment] 2020-05-29 15:26
Duplicate of #1350.

**Comment by shubhankarsharma00** [comment] 2020-05-29 16:12
Can we close issue from GitHub mobile?

**Comment by mahmodHammad** [comment] 2020-06-02 11:53
![more button issue](https://user-images.githubusercontent.com/41790090/83516989-643f9080-a4d8-11ea-9803-cb121faf2ca6.gif)

i was going to report it too 😃

**Comment by nitin10s** [comment] 2020-06-02 17:34
Duplicate of #1350

**Closed by nitin10s** 2020-06-02 17:34 UTC
Labels: 🐞 bug
