### ISSUE TITLE
Issue with add collabarator input field

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4373] opened 2023-12-12 18:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As shown below the input field is shrinked 

![Screenshot 2023-12-12 233111](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/47303db9-cddd-405f-bbcc-7c4939a8ec50)

### Steps To Reproduce

--login
--click dashboard
--pick a project
--click on "+ Add a Collaborator"

### Expected Behavior

Have to make the input field align with the add members box

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by gaus07** [comment] 2023-12-13 19:43
@Malavi1 Are you done with this issue ? or i can try it !...

**Comment by tanmoysrt** [comment] 2023-12-14 05:05
Closing as duplicate of #4330

**Closed by tanmoysrt** 2023-12-14 05:05 UTC
Labels: 🐞 bug, pending triage
