### ISSUE TITLE
Improve the group page

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerse#544] opened 2019-11-06 11:18 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the group page doesn't contain any information about what the group is and how it works. So, if a new user would open it he would have no idea about the working of it.

**Describe the solution you'd like**
Make the group page more attractive by improving it's UI. Also add the details related to the working of the group. If not so add a link at the bottom to the documentation of the group page.

**Add screenshots**
![Screenshot from 2019-11-08 22-46-04](https://user-images.githubusercontent.com/44617923/68497054-ba698f80-0279-11ea-9b1a-6f11cb546f9a.png)

**Are you working on this? (Yes/No)**
No, this task is for GCI students.

**Comment by ShreyaPrasad1209** [comment] 2019-11-07 14:58
Could you add a link or screenshot for better understanding?

**Comment by deepak2431** [comment] 2019-11-07 16:10
@ShreyaPrasad1209 Thanks for the review. Sure, I will add a screenshot.

**Comment by aayush-05** [comment] 2019-11-10 12:49
**Duplicate Issue**
This issue has already been raised under #527

You can close this one

**Comment by tachyons** [comment] 2019-11-12 11:43
Duplicate of #527

**Closed by tachyons** 2019-11-12 11:43 UTC
