### ISSUE TITLE
Toolbar not visible in the simulator [New UX]

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1071] opened 2020-03-08 08:43 UTC
**Describe the bug**
This toolbar is present but not visible in the simulator in the new UX.
![image (2)](https://user-images.githubusercontent.com/16988558/76159431-60ed7080-6146-11ea-9431-12a2e34bcf33.png)

This is because we're using Bootstrap 4 which has dropped the support for Glyphicons. Since we are already using Font-Awesome, we can use it as a replacement.

**To Reproduce**
1. Go to Simulator. 

**Expected behaviour**
The toolbar should be basically made visible.

**Screenshots**
![FireShot Capture 176 - CircuitVerse - Digital Circuit Simulator online - 127 0 0 1](https://user-images.githubusercontent.com/16988558/76159451-91350f00-6146-11ea-9a30-acaa20da1ffe.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Ananthavijay** [comment] 2020-03-08 08:44
Duplicate of https://github.com/CircuitVerse/CircuitVerse/issues/1041

**Comment by Shivansh2407** [comment] 2020-03-08 08:44
Similar to #1041 . I am working on it @nitin10s

**Closed** 2020-03-08 08:45 UTC
