### ISSUE TITLE
🐞 Bug When clicked on Gmail new blank web page opens 

### ISSUE THREAD

**Issue by sahiladit** [CircuitVerse/CircuitVerse#5224] opened 2024-12-13 11:54 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

When I clicked on the gmail of circuitverse , new untitled  web page got opened.

### Steps To Reproduce

1.Open 'About' page of circuit-verse.
2.Click on the gmail.  

### Expected Behavior

A draft email should open with the receiver gmail as the gmail of circuit-verse.

### Screenshots

https://github.com/user-attachments/assets/b546cb40-e0ff-4cd5-a3b6-9e7559d10392

### Device Information [optional]

```markdown
- OS:MacOS
- Browser:Chrome 
- version:
```

### Are you working on this issue?

Yes

**Comment by sahiladit** [comment] 2024-12-13 12:23
strange , doesn't work on my machine ,might be browser issue.

**Comment by salmoneatenbybear** [comment] 2024-12-13 12:33
Which browser ?

**Comment by salmoneatenbybear** [comment] 2024-12-13 12:35
Let me check if it's working on windows machine, the above was from Linux Ubuntu chrome

**Comment by salmoneatenbybear** [comment] 2024-12-13 12:35
In windows also it's working for chrome

**Comment by salmoneatenbybear** [comment] 2024-12-13 12:37
Probably something related to your browser permissions

**Comment by andycandy** [comment] 2024-12-13 19:39
It doesn't depend on browser, its set in default mail action of your OS, its like saying yt app didn't open when you clicked a yt video link from whatsapp, when you haven't set yt as your default action app for that link type.

**Comment by salmoneatenbybear** [comment] 2024-12-13 23:43
Then i think this issue can be closed, right?

**Comment by Saipradyumnagoud** [comment] 2024-12-14 04:52
can You please assign me the issue I will solve the issue

**Comment by salmoneatenbybear** [comment] 2024-12-14 05:46
@Saipradyumnagoud this is not a verified issue

@sahiladit please close this issue

**Comment by Kartikayy007** [comment] 2024-12-14 08:24
Thank you for reporting the issue, @sahiladit  After reviewing the details, it appears this behavior is specific to your device and might be caused by browser or system-level configurations, as others (including myself) could not replicate it.

**Closed** 2024-12-14 13:52 UTC
Labels: 🐞 bug, pending triage
