### ISSUE TITLE
Two overlapping x-icons to close a window

### ISSUE THREAD

**Issue by Logicless-Coder** [CircuitVerse/CircuitVerse#1831] opened 2020-10-23 09:25 UTC
**Describe the bug**
In the Dec-Bin-Hex-Converter and the BooleanLogicTable window, you can see 2 overlapping x-icons in the top-right corner of the window. Once, you hover over it, one of them becomes invisible. 

**To Reproduce**
1. Go to [https://circuitverse.org/simulator](https://circuitverse.org/simulator)
2. Click on Tools in the menu bar on the top
3. Open either Combinational Analysis or Hex-Bin-Dec-Converter
4. Hover over the close (x) icon to better see the difference

**Expected behavior**
I don't think the one that gets invisible over hover was supossed to be there in the first place. It may have stayed there when the icons were changed. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59042344/96986004-a5dfdf00-153e-11eb-86fd-2edacd5088f9.png)

On hover:
![image](https://user-images.githubusercontent.com/59042344/96986348-26064480-153f-11eb-91bc-6f3b40ecee86.png)

**Device Information [optional]:**
 - OS: Windows 10 Home v. 2004 build 19041.572
 - Browser: Firefox Developer Edition 83.0b3 (64-bit)

**Are you working on this issue? (Yes/No)**
I want to work on this issue.

**Comment by Logicless-Coder** [comment] 2020-10-23 09:42
I wanted to work on this issue, but I don't know Ruby on Rails.

**Comment by shivamparashar165** [comment] 2020-10-29 11:12
@Logicless-Coder 

It is an simple bug in CSS file. This is happening due to jQuery UI CSS. We can add embedded style **(backgound-image:none)** for all of the element which have this type of bug.

It will fix the issue.

@satu0king Sir, Give them if he would like to work or able to fix this issue. I am here also if any further help will be needed.

**Comment by satu0king** [comment] 2020-11-01 11:43
Check if the issue is present in https://beta.circuitverse.org/simulator. If not, please close this issue.

**Comment by abstrekt** [comment] 2020-11-05 06:12
It is not present in new UI.

**Closed** 2020-11-20 11:47 UTC
Labels: 🐞 bug
