### ISSUE TITLE
Counter + TriState Not Working in my SAP-1

### ISSUE THREAD

**Issue by simon-tiger** [CircuitVerse/CircuitVerse#434] opened 2019-09-04 18:35 UTC
Inspired by Ben Eater's 8-bit Breadboard Computer, I'm trying to build the [SAP-1 processor in CircuitVerse](https://circuitverse.org/users/7241/projects/22541). I'm on the program counter. It seems like it is counting, but it is in conflict with the Accumulator, even though the wasn't enabled.

I would think that, if the counter is enabled, but the accumulator isn't, it would just be happy outputting to the W Bus, without conflict.

![image](https://user-images.githubusercontent.com/21979673/64281204-e6ebed00-cf52-11e9-8fca-2eafe4353de5.png)

Strangely, it seems like the error doesn't occour when I disconnect the accumulator from the W Bus:

![image](https://user-images.githubusercontent.com/21979673/64281407-5a8dfa00-cf53-11e9-9910-064382ac13e9.png)

**Comment by satu0king** [comment] 2019-09-04 19:04
This is the same issue faced in #236 . The issue is the tristate handling code right now doesn't work correctly across subcircuits. We are looking into it. For now try and get all tristate buses on one circuit itself.

**Comment by simon-tiger** [comment] 2019-09-05 08:45
Hmmm...

@satu0king The other TriState circuits work here!

**Comment by satu0king** [comment] 2019-09-05 08:47
@simon-tiger , no the issue is when the tristate is inside the circuit. A simple fix is to bring the wire controlling the tristate and the tristate outside.

**Comment by ciphereck** [comment] 2020-03-06 09:03
@tachyons @nitin10 we can close this issue since it's same as #236

**Comment by tachyons** [comment] 2020-03-06 10:21
Duplicates #236

**Comment by Ananthavijay** [comment] 2020-03-06 10:22
@ciphereck you have pinged the wrong person, Nitin's id is nitin10s

**Closed** 2020-03-14 00:09 UTC
Labels: duplicate, no-issue-activity
