### ISSUE TITLE
Improve notification page

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#2861] opened 2022-01-30 14:28 UTC
**Describe the bug**

1. No Profile Image 
2. On clicking notification card, it throws up a 404 error
 saying `OOPS, THE PAGE YOU ARE LOOKING FOR CAN'T BE FOUND!`,
( ig because of GET request instead of POST).

**To Reproduce**
1. Go to 'circuitverse.org > notifications'
2. Click on 'any notification card'
3. See an error

**Expected behavior**
1. Display profile Image.
2. Error should be resolved.

<img width="1380" alt="Screenshot 2022-01-30 at 7 32 41 PM" src="https://user-images.githubusercontent.com/76155456/151703589-93fd216a-609b-4cf8-a367-ec95af91924b.png">

**Device Information [optional]:**
 - OS: MacOS
 - Browser Chrome
 - Version current

**Additional context**

Mentioning One exceptional case, Idk why this happens and I cannot reproduce it, Just mentioning it

One notification repeats at the same time, like spam notifications 

<img width="1180" alt="Screenshot 2022-01-30 at 7 42 37 PM" src="https://user-images.githubusercontent.com/76155456/151703696-dc460914-06a3-4704-ab48-317d757be9f2.png">

Only forked 1 project but get 8 notifications (7 marked as read)

**Comment by rachit3006** [comment] 2022-01-30 14:42
Are you working on this? If not can I work on it, please?

**Comment by mudassir1231** [comment] 2022-01-30 15:32
can i work on this issue

**Comment by rachit3006** [comment] 2022-02-02 17:35
@pulkit-30 can you assign this issue to me?

**Comment by rachit3006** [comment] 2022-02-02 17:47
Should opening the notification in the screenshot given above open the project page?

**Comment by rachit3006** [comment] 2022-02-05 20:43
@pulkit-30 there is an open notification button which on click does nothing currently. It seems to me that it was made so that the notification content would be visible once it is clicked but I think that the open notification option is not needed. Even without it the notifications are looking pretty minimalistic and are visible directly. So should I remove the open notification option? @tachyons can you provide your views too?

**Comment by rachit3006** [comment] 2022-02-07 11:29
@vedant-jain03 what views do you have regarding the above?

**Comment by tachyons** [comment] 2022-02-07 11:47
Duplicate of https://github.com/CircuitVerse/CircuitVerse/issues/2321

**Closed by tachyons** 2022-02-07 11:47 UTC
Labels: 🐞 bug
