### ISSUE TITLE
🐞 Bug : Responsiveness of Comments .

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4231] opened 2023-10-30 13:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When long comments are present, the comment box overflows and disrupts the width of the website.
### Video of Bug : 

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/4aaa9907-5764-4acb-8a70-9b56e194da61

### Steps To Reproduce

1. Go to any project page and find comment section
2. write a comment with long words
3. Convert the website to small screen.
**_See the error that comment section is not responsive ._**

### Expected Behavior

The comment box should be responsive. 
### Video of Solution:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/cdffebe3-1f69-4966-81bc-c812570c3c8b

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by parthksingh1** [comment] 2023-11-02 09:46
@shauryag2002 @vedant-jain03 @tanmoysrt please assign me this issue as a new contributer it will be helpul for me

**Comment by tanmoysrt** [comment] 2023-11-02 14:02
The issue has been verified!

**Comment by niladrix719** [comment] 2023-11-02 14:12
i am up for the work if nobody is there

**Comment by shauryag2002** [comment] 2023-11-02 14:36
Yes , you can @tanmoysrt 

> If you don't mind @shauryag2002 can I assign another one to this?

Yes @tanmoysrt ,You can.

**Comment by tanmoysrt** [comment] 2023-11-02 14:39
Hi @parthksingh1 you can start working on this !

**Comment by lalitkumawat1m** [comment] 2023-11-16 07:45
Hi @tanmoysrt is this issue still open? Can I work on this issue?

**Comment by tanmoysrt** [comment] 2023-11-16 07:55
Hi @parthksingh1 any update ?

**Comment by tanmoysrt** [comment] 2023-11-21 09:11
@parthksingh1 it's long time, and there is no update, so I am unassigning this issue

**Comment by tanmoysrt** [comment] 2023-11-21 09:11
@lalitkumawat1m you have been assigned. You can start working on this issue

**Comment by Jeevan-Neupane** [comment] 2023-11-24 06:49
Please assign it to me i can work on this if possible

**Comment by MaYaNkKashyap681** [comment] 2023-11-29 17:06
If no one else is working on this issue then could you please assign this issue to me? I would love to work on this.

**Comment by Kashyap-Rishi** [comment] 2023-11-29 19:53
@tanmoysrt , I'm highly interested to quickly work and fix this issue. Could you assign it to me if possible

**Comment by deepak05kr18** [comment] 2023-12-09 16:12
@tanmoysrt @shauryag2002  as it been a while and the issue is yet to be solved can I get assign to it.

**Comment by tanmoysrt** [comment] 2023-12-09 19:02
Hi @MaYaNkKashyap681 @Kashyap-Rishi, if you like to solve the issue please let us know, else will assign the next person.

**Comment by MaYaNkKashyap681** [comment] 2023-12-10 05:13
Yes, sure I want to work on this.

**Comment by ravi1718** [comment] 2023-12-10 05:50
@tanmoysrt  please assign me this issue i want to work on this issue as i begineer i will gain some knowledge and experience by contributing please assign me this issue

**Comment by Jeevan-Neupane** [comment] 2023-12-10 11:37
@tanmoysrt  I want to work on this issue

**Comment by nisha-laur** [comment] 2023-12-17 23:07
@tanmoysrt @shauryag2002 I would like to work on this issue can you please assign this issue to me .

**Comment by fillingtothemomo** [comment] 2023-12-22 19:40
Hello @tanmoysrt I would like to take up this issue, can you assign it to me.

**Comment by nikhilhuirem** [comment] 2023-12-26 05:22
Hey @tanmoysrt, I know the solution to this issue. Do you think I should move ahead?

**Comment by tanmoysrt** [comment] 2023-12-26 14:40
Hi @PR4NJ41 , would you like to work on this issue ?

**Closed** 2024-01-02 17:58 UTC
Labels: 🐞 bug
