### ISSUE TITLE
ui: sign-up page revamp

### ISSUE THREAD

**Issue by Waishnav** [CircuitVerse/CircuitVerse#3635] opened 2023-03-02 11:20 UTC
### Is your feature request related to a problem? Please describe

This UI revamp is meant to increase the visibility of O-Auth options like signing up with google, github, facebook, etc.
also improves the hierarchy of UI elements on the page.

### Describe the solution you'd like

|                                          before                                          |                                         after                                          |
| :-------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| ![](https://user-images.githubusercontent.com/86405648/222413763-89dc2615-402f-42d3-9db1-2893c0fcadb6.png) | ![](https://user-images.githubusercontent.com/86405648/222413889-dbdc5938-a6e8-40e3-a331-40db9acec734.png) ![](https://user-images.githubusercontent.com/86405648/222414944-5118e762-b565-4a67-b874-02e374968d6d.png) |

For more details visit this Figma design [here](https://www.figma.com/file/btjwmO8Jq1Q4L0NcraOuT7/circuitverse-ui-updates?node-id=307%3A32&t=COylgeNXKj0GM5y9-1), And go to `login/sign-up revamp` page shown in left sidebar.

### Additional context

This feature is under the fosshack, you need to register [here](https://fossunited.org/login#login). You can join #fosshack-students channel in slack for any doubts and support

### Are you working on this?

No

**Comment by ishaan9006** [comment] 2023-03-02 11:30
Hey @Waishnav! Can I work on this? Also, I'm new to open source so can you tell me the directory in which I have to add the page?

**Comment by Waishnav** [comment] 2023-03-02 11:44
@ishaan9006 Hey welcome to CircuitVerse community. If you are new to open source. I would like to tell you that working in open source is skill. You need to understand the what issue is first and then search in the codebase where to edit. 
Here in this case you can approach this issue by going to sign up page [here](https://circuitverse.org/users/sign_up). And search for CSS class in the codebase. You can search it in vs-code `Ctrl + Shit + F` or you can search that particular CSS class in github as well.
And you can understand the where to edit there on.
Hope you get it.

**Comment by ishaan9006** [comment] 2023-03-02 11:51
@Waishnav Got it! Thank You.

**Comment by Waishnav** [comment] 2023-03-02 11:53
Now you can start working on the issue.

**Comment by Waishnav** [comment] 2023-03-02 11:53
Now you can start working on the issue.

**Comment by ishaan9006** [comment] 2023-03-02 17:58
@Waishnav I'm done with the code. Good enough to make a pull request??
![ss](https://user-images.githubusercontent.com/72651834/222512468-318ddb65-b202-4ec7-bca5-5de226cd9474.png)

**Comment by Waishnav** [comment] 2023-03-02 18:18
@ishaan9006  Could you let me know if you're done with the first design (giving options to the user like signing up with google, email etc.. ) when the user goes to the sign-up page as mentioned in the issue?
Also you seems like not used the CSS (height, width etc) mention in the Figma in left side under the `inspect` tab.

**Comment by ishaan9006** [comment] 2023-03-03 03:38
@Waishnav I thought only one design had to be made.
1) I'll make the first one too but do I have to make a separate file for that?
2) The size is the same as mentioned in Figma, I will adjust the padding.

**Comment by Waishnav** [comment] 2023-03-03 06:20
No. You don't need to make a separate file for that. So the user's journey is like this -> when clicking on `sign up with email` button, user will get the sign up form. you just need to manipulate the DOM for this, don't make another route IMO.
CC: @vedant-jain03 WDYT?

**Comment by ishaan9006** [comment] 2023-03-03 07:19
@Waishnav I tried but I'm not able to manipulate DOM, can you help me out with this??

**Comment by Waishnav** [comment] 2023-03-03 10:17
You need to create a onclick function for that button so that we can toggle between the two screen. (`display: none` and `display: block`)

**Comment by Waishnav** [comment] 2023-03-04 08:32
@ishaan9006 any updates?

**Comment by Malavi1** [comment] 2023-03-05 10:48
If the issue is still open I would like to work on this issue !!

**Comment by Malavi1** [comment] 2023-03-05 10:52
If it is still open I would like to work on this issue!

**Comment by Waishnav** [comment] 2023-03-05 11:58
@ishaan9006 Are you done with the issue or you are not able to do it?
Leme know. CV Community is here to help.

**Comment by ishaan9006** [comment] 2023-03-05 14:04
@Waishnav  Hey! I'm done with both screens but I'm still struggling with the toggle function.

**Comment by AbhishekCS3459** [comment] 2023-03-09 05:58
@ishaan9006 Do You need Any Help I feel happy to do so

**Comment by vedant-jain03** [comment] 2023-03-13 04:10
Due to inactivity @ishaan9006 I am unassigning this issue.
@Malavi1 Would you like to work on this?

**Comment by Luci04** [comment] 2023-03-14 07:22
I want to work on this issue assign this to me

**Comment by jonhoa** [comment] 2023-03-25 04:03
Hello team, I'm new to OSC but I'd love to contribute to circuitverse. Do let me know how I can help out 🤞

**Comment by BANGBANG1999** [comment] 2023-03-25 15:15
I am also willing to work on the issue. Can I do that ?

**Comment by sahilrajput18** [comment] 2023-03-30 10:39
Hey ! if this issue is still open i would like to contribute as well

**Comment by nithinkatta** [comment] 2023-03-31 18:48
Hey hi @Waishnav if @Luci04 could not solve the issue I would like to take up the challenge. Recently I made a web application so I could solve this issue as soon as possible.

**Comment by Aryan-Mishra24** [comment] 2023-04-02 23:45
i'd love to work on this issue or help and collaborate with whoever is working on it

**Comment by mayankjain25** [comment] 2023-04-08 12:52
Would love to work on this issue.

**Comment by vedant-jain03** [comment] 2023-04-08 13:02
@mayankjain25 Sure, go ahead

Let me know if you need any help!

**Comment by subhajit20** [comment] 2023-04-14 19:06
@mayankjain25 hello! do I need to create those figma ui mentioned above ?

**Comment by uday-kiran-001** [comment] 2023-04-22 12:00
Hey, is anyone working on this issue? If not, I'm willing to start working on it?
@Waishnav @vedant-jain03

**Comment by imanshu03** [comment] 2023-04-22 20:00
@Waishnav @vedant-jain03 Is anybody working on this issue currently ?

**Comment by webbedpiyush** [comment] 2023-04-23 07:29
Hey I noticed that Issue #3635 is currently assigned to @mayankjain25 but there hasn't been progess, so I would like to request that it be reassigned to me. I am interested in working on this issue and believe that I can make progress on it.
@Waishnav @vedant-jain03

**Comment by SimardeepSingh1450** [comment] 2023-05-07 21:53
@vedant-jain03 @Waishnav since i am already done with the ui-login page revamp, I think i can complete this issue quickly , and there has not been much progress for long time from @mayankjain25 , so if possible can you assign this issue to me?

**Comment by afeefuddin** [comment] 2023-05-14 17:04
Hey @vedant-jain03  @Waishnav Is this issue still open. I want to work on this issue please assign this issue to me.

**Comment by DkRadhey** [comment] 2023-07-25 08:35
Hey @Waishnav @vedant-jain03  is this issue still open. If yes, could you please assign this to me.

**Comment by Lalitmohanjoshi07** [comment] 2023-08-03 05:30
@vedant-jain03 if this issue is still open, I would like to work on it

**Comment by sharma62** [comment] 2023-08-15 12:34
### Solution 💯 

### Answer 👍 
Now according to me following UI design is more effective.

![222413889-dbdc5938-a6e8-40e3-a331-40db9acec734](https://github.com/CircuitVerse/CircuitVerse/assets/75290099/262f4282-bcda-4dfe-8696-037fd6f2f234)

Reason: Because of User Experience is great, I mean easy to pass O-Auth signing up with google, GitHub, Facebook, etc.
 >Here is 4 option which help one-click solution.
  1. sign up with Google.
  2. sign up with Email.
  3. sign up with Facebook.
  4. sign up with GitHub.
  
> Now apart from this if tackle user Already Registered / Sign it. The solution is given Here Link `Sign In` which redirect to Sign In screen.  


### Description: 
Have many times user wants to access the website & go to explore inside it, if the 1st step goanna complex, I mean user input is large size then user back down their step and change their mind & finally not pass signing process.

### Advantage
 Easy to use & simple UI or signing process. To target large number of audiences.

**Comment by harshsharma-11** [comment] 2023-08-16 17:49
hello @Waishnav  please assign the issue to me if issue is still open!!!!!!!!!!!!!

**Comment by connectnitesh** [comment] 2023-08-18 08:22
Hey @Waishnav I would like to work on this issue.

**Comment by LavanyaLahari811** [comment] 2023-08-20 17:00
Hello @Waishnav ,I am new to open source. If this issue isn't assigned to anyone, I can work on it

**Comment by brf153** [comment] 2023-08-24 13:47
Hello @Waishnav , please assign this issue to me. By the way can we directly work on the code and make a pr?

**Comment by niladrix719** [comment] 2023-08-24 15:23
@brf153 Hi its not recommended by mentors to have a direct PR, first get assigned to the issue by a mentor  to make a PR.

**Comment by harshsharma-11** [comment] 2023-08-24 16:14
@brf153 bro if that issue is your's then at that case can we make directly pr

**Comment by niladrix719** [comment] 2023-08-24 17:24
@harshsharma-11 Hi Harsh that's not how it works, A issue first needs to be approved by the maintainers before assigning anyone to work on

**Comment by harshsharma-11** [comment] 2023-08-24 17:43
> @harshsharma-11 Hi Harsh that's not how it works, A issue first needs to be approved by the maintainers before assigning anyone to work on

but sometimes i created an issue and i ask the issue to assign to me and before assigning someone makes pr and that get merged.Now all my hardwork get ruined

**Comment by vashukashyap** [comment] 2023-09-16 05:19
Hello sir, I am new to open source. I found that this issue is open and have 'Good first issue' label. Can I work on this issue?
please let me know so that I can start contributing.
thankyou.

**Comment by hrshkshri** [comment] 2023-10-07 04:15
Hey @Waishnav @vedant-jain03, can you assign me this one I can fix this...?

**Comment by theslowdeveloper** [comment] 2023-10-14 15:58
@vedant-jain03 @Waishnav  can i work on this issue ? it has been idle for quite a time, I also have suggested another design in #4092

**Comment by Jeevan-Neupane** [comment] 2023-11-24 06:42
@vedant-jain03 assign this to me . I would love to work on this.

**Comment by Nikuunj** [comment] 2023-11-28 17:39
I have some experience in programming languages like html , css , js , react . I am passionate about open-source and have recently participated in Hacktoberfest 2023. I am now seeking mentorship to improve my skills in open-source development. I am keen to contribute to your projects and would appreciate your guidance on how to get started.

**Comment by Ranjeet0062** [comment] 2023-12-15 16:34
Hello @Waishnav,  I have some experience in programming languages like html , css , js , react and node.js. I am passionate about open-source.if this issue is still alive then i want to contribute on it

**Comment by nisha-laur** [comment] 2023-12-25 10:27
@vedant-jain03 as there has been no activity on this issue by @mayankjain25  . I would like to work on this issue . Can you please assign it to me .

**Comment by Pulkit0729** [comment] 2024-01-21 07:39
Hi @Waishnav , as there has been no activity in this issue i will be giving it a try. I have looked at the above and will soon raise a PR.

**Comment by nitin10s** [comment] 2024-01-22 11:44
The design has a lot of issues, we won't be proceeding ahead with it for the moment guys

**Closed by nitin10s** 2024-01-22 11:44 UTC
Labels: good first issue, 🌟 feature, ui, fosshack

**Comment by Pulkit0729** [comment] 2024-01-22 14:55
Alright
