### ISSUE TITLE
🐞 Bug : - Username Not Visible in Navbar due to Insufficient Screen Width

### ISSUE THREAD

**Issue by charu1603** [CircuitVerse/CircuitVerse#4393] opened 2023-12-18 09:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the screen width is decreased, the username in the navbar is not visible and disappears in the simulator. This issue is impacting the user experience as it prevents users from accessing their account-related information easily.

![Screenshot (527)](https://github.com/CircuitVerse/CircuitVerse/assets/96014425/38ac6498-4695-4442-940b-b8c6a7e00bf5)

![Screenshot (528)](https://github.com/CircuitVerse/CircuitVerse/assets/96014425/da6d2946-b5cb-4a47-a61c-ecc4f8b5f781)

### Steps To Reproduce

1)Go to https://circuitverse.org/simulator
2)Navigate to the navbar where the username is displayed.

### Expected Behavior

The username in the navbar should remain visible and accessible regardless of the screen width. Users should be able to see their username at all times for a seamless navigation experience.

### Device Information [optional]

```markdown
- OS:Windows
- Browser:chrome
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment] 2023-12-18 15:57
duplicate of #4331

**Closed by tanmoysrt** 2023-12-18 15:57 UTC
Labels: 🐞 bug, pending triage
