### ISSUE TITLE
🐞 Bug flashing red screen when refresh the page

### ISSUE THREAD

**Issue by JamesCartar** [CircuitVerse/CircuitVerse#4528] opened 2024-01-06 14:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When refreshing the page, most of the time, a red flash screen appears for a second which is not good for user experience.

### Steps To Reproduce

1. Go to the home page
2. Refresh the page.

### Expected Behavior

Should not show the red screen when refresh.

### Screenshots

[screen-capture (1).webm](https://github.com/CircuitVerse/CircuitVerse/assets/90121395/fe89ca60-ebef-4d74-87e3-00fef2952e7d)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by gunjjoshi** [comment] 2024-01-07 17:27
I would love to work on it, please assign me.
Thanks.

**Comment by tanmoysrt** [comment] 2024-01-08 20:22
Closing as duplicate of #4394

**Closed by tanmoysrt** 2024-01-08 20:22 UTC
Labels: 🐞 bug, pending triage
