### ISSUE TITLE
Sign up error messages

### ISSUE THREAD

**Issue by Tanish0019** [CircuitVerse/CircuitVerse#554] opened 2019-11-06 16:56 UTC
**Is your feature request related to a problem? Please describe.**
While signing up if you run into an error like using an already taken email. The error message show is poorly displayed.

**Describe the solution you'd like**
The errors should be shown like flash messages or like helper text under the input field.

**Additional context**
![Screen Shot 2019-11-06 at 10 25 12 PM](https://user-images.githubusercontent.com/30210495/68319452-5cf00a00-00e4-11ea-8ee5-47b8d4a09801.png)

**Are you working on this? (Yes/No)**
No

**Comment by plxity** [comment] 2019-11-06 17:10
@Tanish0019 This issue has been already raised. You may close this.

**Comment by ankitkataria** [comment] 2019-11-09 17:53
Duplicate of #548

**Closed by ankitkataria** 2019-11-09 17:53 UTC
