### ISSUE TITLE
circuit verse help button is not working for most components 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1393] opened 2020-04-11 17:37 UTC
**Describe the bug**
circuit verse help button is not working for most components 

**Expected behavior**
user shouldn't get a blank page for some component if he clicked on the help button,

**Screenshots**
![helper](https://user-images.githubusercontent.com/41790090/79050439-479a8100-7c2a-11ea-8126-8dd81bd1c3d9.gif)

**Additional context**
The reason for this bug is that the helpline is not defined on all components[52] it's only defined for only 18 
![image](https://user-images.githubusercontent.com/41790090/79050472-8defe000-7c2a-11ea-869c-259ffa65264a.png)
so it will be undefined for most cases
![image](https://user-images.githubusercontent.com/41790090/79050553-09519180-7c2b-11ea-9a5b-8e59ff229b8b.png)
**some solutions that may fix it **

1. add helpline for all components prototype ->it's already done at the meta.json file at this PR #1392 so we will just copy past

1.  make a check to hide the help button if obj.helplink is undefined
**Are you working on this issue? (Yes/No)**
NO

**Comment by Ananthavijay** [comment] 2020-04-11 17:39
Duplicate of https://github.com/CircuitVerse/CircuitVerse/issues/1317
Fix: https://github.com/CircuitVerse/CircuitVerse/pull/1319

This issue can be closed.

**Comment by mahmodHammad** [comment] 2020-04-11 17:49
i think the best solution for this is to **totally delete the helpline** from all component and **rename IDs of the doc page to have the same name as component's name**  then we will fix it with just **2 lines** like this 
![image](https://user-images.githubusercontent.com/41790090/79050822-d8725c00-7c2c-11ea-9a2d-e8683a33e786.png)
this will make the code  shorter about 50 lines, and remove the duplication of this "https://docs.circuitverse.org/#/" every time 
![image](https://user-images.githubusercontent.com/41790090/79050901-4ae33c00-7c2d-11ea-871e-24ebb6cda2f4.png)

**Comment by abstrekt** [comment] 2020-05-12 12:34
Duplicate, can be closed.

**Comment by abstrekt** [comment] 2020-05-12 18:41
@nitin10s

**Closed** 2020-05-12 18:44 UTC
