### ISSUE TITLE
Holding backspace and dragging corrupts simulator

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#122] opened 2019-02-21 23:03 UTC
This is a strange one.

Holding down backspace and dragging your mouse will corrupt the simulator. I have absolutely no diagnosis nor explanation as to how or why, I just know it does happen. Pretty consistently too.

**Comment by Amansingla97** [comment] 2019-03-03 10:11
Can you please give me more details on this issue?.I am not able to reproduce this issue.

**Comment by satu0king** [comment] 2019-03-03 14:44
@armudgal, what is triage?

**Comment by armudgal** [comment] 2019-03-03 15:09
@satu0king issues under `triage` needs to be looked upon once again after reproducing and confirming the issue, to figure out the difficulty in resolving it.

**Closed** 2020-03-14 00:09 UTC
Labels: no-issue-activity, triage
