### ISSUE TITLE
Error-Message style missing in "Assignment" section 

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4592] opened 2024-01-13 12:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Throughout the application we are showing the error message with only one style as shown in the below. 

![Screenshot from 2024-01-13 17-29-14](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/a03af69a-269a-4b7f-bf95-b436ac361120)
![Screenshot from 2024-01-13 17-38-00](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/a8a4bad9-1672-4d91-8631-9c43e3075ef8)
 
**But assignment error message missing this style.**

![Screenshot from 2024-01-13 17-26-38](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/5e5ce999-0093-4245-b774-8ea06d890c86)

### Steps To Reproduce

_dahsboard->try to create assignment without name_ 

### Expected Behavior

To make it consistent we have to add styling to this section too

![Screenshot from 2024-01-13 17-52-55](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/0a81bec0-e2fa-4282-ad75-fa8ccbff77e9)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by SharanRP** [comment] 2024-01-13 12:46
I think we just need to add CSS styling , or toast to fix this bug, please assign me this issue

**Comment by igennova** [comment] 2024-01-13 15:03
Assign me

**Comment by upsaurav12** [comment] 2024-01-13 17:46
how to reproduce this issue ?

**Comment by priyanshagra** [comment] 2024-01-14 06:08
assign me

**Comment by Malavi1** [comment] 2024-01-14 11:38
> ig i got the issue actually it is showing message but we just need to style the message @Malavi1 right??
> 
> ![image](https://private-user-images.githubusercontent.com/116784047/296540380-a7c5c011-bffb-4f10-86cf-f4a564b4084f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzI0NjAsIm5iZiI6MTcwNTIzMjE2MCwicGF0aCI6Ii8xMTY3ODQwNDcvMjk2NTQwMzgwLWE3YzVjMDExLWJmZmItNGYxMC04NmNmLWY0YTU2NGI0MDg0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQxMTM2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjJkMzFhYzBiYTc0MTEwNDkwZjJkNWExN2RmOWU4NjU5OGE3MmMzZmIyNjI0Njk5MDE3NzI2MWU0MDU3MDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MXIuTgDt2tB57KHQdLgBWSBMrEKcEQZWeC955FHOp2Q)

It is also one of the ways, or as we already have error-message styling simply name the div with that

**Comment by tanmoysrt** [comment] 2024-01-15 05:18
> I think we just need to add CSS styling , or toast to fix this bug, please assign me this issue

You can work on the issue

**Comment by sahilarora02** [comment] 2024-01-18 14:24
Is this issue still open??

**Comment by upsaurav12** [comment] 2024-01-18 14:38
> Is this issue still open??

No this issue is assigned to someone else 
if u dont know that how to know that the issye is assigned to someone then pls check assignees in ``assignee`` tag

**Comment by Chandrachur67** [comment] 2024-01-29 13:11
I would like to work on this if no one is working. (since no pr even after 2 weeks)

**Comment by Chandrachur67** [comment] 2024-01-29 14:23
@tanmoysrt  @Malavi1 I have solved the issue. I hope this is the desired behaviour. 

please assign this to me if possible. I can raise a pr as soon as it is assigned to me. 
I have made the change in all the places where this inconsistency could have occurred.

Image reflecting the change 
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>

<img width="1426" alt="Screenshot 2024-01-29 at 7 50 46 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/97349505/0a963a3e-f9e9-4bda-8f8e-dee42e461038">

</td>
<td>

<img width="1439" alt="Screenshot 2024-01-29 at 7 46 37 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/97349505/10809dd5-d230-4c66-b386-02df62ea2d2e">

</td>

</tr>

</table>

**Comment by tanmoysrt** [comment] 2024-01-29 21:48
Hi @SharanRP any update ?

**Comment by SharanRP** [comment] 2024-01-31 13:15
sorry ,I couldn't find the correct file to make changes

**Comment by tanmoysrt** [comment] 2024-01-31 14:03
Thanks @SharanRP for the update

**Comment by tanmoysrt** [comment] 2024-01-31 14:03
> @tanmoysrt @Malavi1 I have solved the issue. I hope this is the desired behaviour.
> 
> please assign this to me if possible. I can raise a pr as soon as it is assigned to me. I have made the change in all the places where this inconsistency could have occurred.
> 
> Image reflecting the change
> 
> Before	After
> <img alt="Screenshot 2024-01-29 at 7 50 46 PM" width="1426" src="https://private-user-images.githubusercontent.com/97349505/300492329-0a963a3e-f9e9-4bda-8f8e-dee42e461038.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTAwOTMsIm5iZiI6MTcwNjcwOTc5MywicGF0aCI6Ii85NzM0OTUwNS8zMDA0OTIzMjktMGE5NjNhM2UtZjllOS00YmRhLThmOGUtZGVlNDJlNDYxMDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE0MDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxYWUxODBiOTFlMGE5YzhiNmRjNmVjMGU1ODkxNTY1YWJhODg3NDk3N2U3YmE1ZTlkMjI0NGY5ZjFlYTVhNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p4b5IuWCrbBgLelLN06P46p1U9ZvWRDsaUIMCcfVJok">	<img alt="Screenshot 2024-01-29 at 7 46 37 PM" width="1439" src="https://private-user-images.githubusercontent.com/97349505/300492286-10809dd5-d230-4c66-b386-02df62ea2d2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTAwOTMsIm5iZiI6MTcwNjcwOTc5MywicGF0aCI6Ii85NzM0OTUwNS8zMDA0OTIyODYtMTA4MDlkZDUtZDIzMC00YzY2LWIzODYtMDJkZjYyZWEyZDJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE0MDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiOTJlNGNkZDIzMmFlNTdlODhmMzBkOWNhZWMyNDNlYjJhNjgzMWQxYzhmNTlkMmZmZjlhNmQyN2Q3ZDc1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMJPCZpYn_71Fjnuok5p4dj7fM7tEUwdgykjtsKsWlY">

You can raise PR for the issue fix

**Comment by Chandrachur67** [comment] 2024-02-01 19:18
Hey @tanmoysrt , I have raised the pr. thank you.

**Comment by lavi20** [comment] 2024-02-27 10:02
@tanmoysrt i want to work on this issue please assign this to me

**Comment by upsaurav12** [comment] 2024-02-27 15:03
hey @lavi20 for this issue there is already raised pr opened so you can check other issue that are not assign to someone else 
or you can make you own issue also

**Closed** 2024-03-07 05:43 UTC
Labels: good first issue, 🐞 bug, pending triage
