### ISSUE TITLE
🐞 Bug : one image of recent circuit is not shown

### ISSUE THREAD

**Issue by Min2who** [CircuitVerse/CircuitVerse#4173] opened 2023-10-12 10:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when i go to the home page and scroll to the recent circuit section the ( exp new ) image is not showing
![Screenshot (70)](https://github.com/CircuitVerse/CircuitVerse/assets/127925465/676599f1-de53-404f-a9cc-16153b82a624)

### Steps To Reproduce

1.circuitverse.org
2.In the home page see the recent circuit section

### Expected Behavior

the image should be clear instead of not appearing

### Screenshots

![Screenshot (70)](https://github.com/CircuitVerse/CircuitVerse/assets/127925465/20a0290f-fe2f-4151-9b84-a773f72d6111)

### Device Information [optional]

```markdown
- OS:windows 10
- Browser: chrome 
- version:
```

### Additional context

please assign me this issue

### Are you working on this issue?

Yes

**Comment by niladrix719** [comment] 2023-10-12 10:27
@Min2who i think its just internet issue and not a bug

**Comment by Min2who** [comment] 2023-10-12 10:29
i guess it is a bug

**Comment by Min2who** [comment] 2023-10-12 10:29
i guess it is a bug
can you recreate it

**Comment by tanmoysrt** [comment] 2023-10-16 07:29
On the website there is no issue currently, it may be due to a failure in the preview image generation at that time.
If you can't reproduce this anymore, please close the issue

cc @Min2who

**Closed** 2023-10-17 08:22 UTC
Labels: 🐞 bug, pending triage
