### ISSUE TITLE
Unsuitable width of form fields with error 

### ISSUE THREAD

**Issue by shukapurv** [CircuitVerse/CircuitVerse#2790] opened 2022-01-16 22:46 UTC
**Describe the bug**
Unsuitable width of fields with error in sign-up page.

**To Reproduce**
1. Go to 'Sign up page'
2. Sign up with all fields blank.

**Expected behavior**
Width of the fields should be fixed.

**Screenshots**
![Screenshot from 2022-01-17 04-10-44](https://user-images.githubusercontent.com/73848723/149681134-0d21ed59-6ac0-4136-80c0-6d2f04ba95fe.png)

**Device Information [optional]:**
 - OS: Ubuntu
 - Browser: Chrome

**Are you working on this issue? Yes**

**Comment by Prerna-0202** [comment] 2022-01-17 05:35
Duplicate of #2603

**Comment by shukapurv** [comment] 2022-01-17 12:35
@Prerna-0202 sorry for the Duplicate issue but I think #2603 is only related to the password field's positioning and this issue is related to width of all the fields.

**Comment by KhanFiza896** [comment] 2022-01-25 11:02
Is this issue still open?

**Closed** 2023-10-21 08:53 UTC
Labels: 🐞 bug
