### ISSUE TITLE
[BUG] "Gates" look ugly when increase input size

### ISSUE THREAD

**Issue by sanctophagus** [CircuitVerse/CircuitVerse#207] opened 2019-03-06 20:46 UTC
![and_gate](https://user-images.githubusercontent.com/31550423/53911977-e47d0900-407d-11e9-933e-07b45e8732a9.png)

When trying to increase the input size beyond 5, all the `Gates` (exception: not gate) look not so visually appealing.

**Comment by sanctophagus** [comment] 2019-03-06 20:46
I don't know if this was intentional, but if it is not I self assign this one to me.

**Comment by sanctophagus** [comment] 2019-03-06 20:48
@fpintos @satu0king Like with multiplexers, can we increase the size of the gates? You views?

**Comment by jbox144** [comment] 2019-03-06 21:12
I say there should also be an option to adjust the spacing between the inputs of gates.

Otherwise, I'd say this functionality of having gates having multiple inputs was largely thrown together, and not properly implemented. Not that I'm shaming the person who did this, it's not the end of the world.

**Comment by fpintos** [comment] 2019-03-07 02:18
If we do change the size it would have to be optional, otherwise it will break existing circuits.

**Comment by satu0king** [comment] 2019-03-07 02:26
@sanctophagus, Yes this is by design. It has to be functional before visually appealing. Also, an AndGate which grows in size is not very functional as uses will have to keep adjusting the position. The functionality was introduced for multiplexers because there it was more straightforward. 

Also as @fpintos says, if we have an implementation it has to be optional as it will otherwise break the circuits. 

I think this is overkill for now and so I will be closing the issue.  

> Otherwise, I'd say this functionality of having gates having multiple inputs was largely thrown together, and not properly implemented. Not that I'm shaming the person who did this, it's not the end of the world.

@jbox144, you are right in a way, that having multiple inputs has been implemented without much thought. However a lot of different behaviors was experimented and the current behaviour was found to be ideal.

**Closed by satu0king** 2019-03-07 02:26 UTC
