### ISSUE TITLE
navigation bar overlapped with text on Editing project page(In half Screen mode)

### ISSUE THREAD

**Issue by MayankG20** [CircuitVerse/CircuitVerse#1021] opened 2020-03-04 21:48 UTC
**Bug Description**
When we haven't save the project than a popup will appear asking us to save the project on clicking, it asks about name and redirect us to editing project page which has overlapping title with navigation bar.

**To Reproduce**
1. Login
2. Start working on the project
3. A popup will appear:
![Screenshot from 2020-03-05 02-49-13](https://user-images.githubusercontent.com/43454678/75924826-a2072b80-5e8d-11ea-9106-7d8755cbaed8.png)
4. After clicking on ok and entering name in next pop up:
![Screenshot from 2020-03-05 02-49-20](https://user-images.githubusercontent.com/43454678/75924964-e0044f80-5e8d-11ea-9c62-90328f0d73c1.png)
5. On clicking ok this will appear:
![Screenshot from 2020-03-05 02-49-35](https://user-images.githubusercontent.com/43454678/75925019-f5797980-5e8d-11ea-905a-2b6153dffd7a.png)
6. See error as we are not able to read the title due to overlapping.

**Expected behavior**
This will look like this:
![Screenshot from 2020-03-05 03-11-20](https://user-images.githubusercontent.com/43454678/75925685-1ee6d500-5e8f-11ea-9505-d57294a62d2c.png)

**Desktop**
 - OS: Linux
 - Browser: Firefox 
 - Version: 73.0.1

**Are you working on this issue?**
Yes

**Comment by Shivansh2407** [comment] 2020-03-05 03:41
Can I fix this @MayankG20 ?

**Comment by rishipurwar1** [comment] 2020-03-05 08:45
I think this issue is in old UI. In new UI, this issue is now fixed.

**Comment by yash15601** [comment] 2020-03-05 08:57
@rishipurwar1   see the browser the problem is in firefox i think which you are using ??

**Comment by MayankG20** [comment] 2020-03-05 19:20
> I would like to work on this @MayankG20 ?

Yeah you can I tried but not able to figure out the correct file for chaning css of that page.

**Comment by MayankG20** [comment] 2020-03-05 19:27
> @rishipurwar1 see the browser the problem is in firefox i think which you are us

> @rishipurwar1 see the browser the problem is in firefox i think which you are using ??

Yeah this problem only arises in firefox but  we have to correct that also

**Comment by rishipurwar1** [comment] 2020-03-06 05:04
I am using chrome.
if this problem is in firefox, we have to fix that.
Anyone working on it?

**Comment by aayush-05** [comment] 2020-03-06 14:09
@MayankG20 please check if it still exists on the latest master because this page had been revamped under new UI

**Comment by MayankG20** [comment] 2020-03-07 07:26
> @MayankG20 please check if it still exists on the latest master because this page had been revamped under new UI

I am new to ruby so can you tell me what is the location of this page inside this repo as i have tried a lot but couldn't figure out

**Comment by aayush-05** [comment] 2020-03-09 07:04
I checked, it is fixed in the new UI. Please close this issue 
![image](https://user-images.githubusercontent.com/47032027/76190134-4f699e80-6202-11ea-9b8c-49f79c8f7ddc.png)
![image](https://user-images.githubusercontent.com/47032027/76190144-509acb80-6202-11ea-903a-f7edb1997a25.png)

**Closed** 2020-03-10 05:40 UTC
